/** @format */
import catan from "../assets/catan.jpg";
import got from "../assets/graotron.jpg";
import gaja from "../assets/projektgaja.jpg";
import terra from "../assets/terramystica.jpg";

export const productsData = [
  {
    id: 1,
    productName: "Catan",
    postDescription:
      "W świecie gier planszowych nieczęsto można trafić na tak ciekawą pozycję jak Osadnicy z Catanu. Jej pierwotny koncept stworzył Klaus Teuber w 1995 roku. Został on wydany w pięciu edycjach, gdzie ostatnia z nich pojawiła się w 2015 roku. Catan, bo tak brzmi uproszczona nazwa serii, szybko zdobywał popularność na rynkach zagranicznych, dzięki czemu zgromadził ponad 10 dużych nagród. Sukces produkcji przełożył się na sprzedaż 22 milionów egzemplarzy w ponad 30 krajach. Od 2002 roku organizowane są mistrzostwa świata, gdzie udział może wziąć maksymalnie dwóch reprezentantów danego kraju. O co chodzi w Catanie? Jako odkrywca dopływasz do nieznanej nikomu wyspy gdzie otoczony wieloma dobrami naturalnymi postanawiasz założyć dwie osady. Szybko się okazuje, że wyspa nie jest niezamieszkała, więc szybko dobudowujesz nowe szlaki handlowe aby móc tworzyć kolejne osady i miasta. Od teraz twoim głównym celem jest jak najszybsze zbudowanie potęgi na wyspie. Rozłożenie i cel gry. W głównej wersji gry udział mogą wziąć maksymalnie 4 osoby. Każdy z graczy otrzymuje na start zestaw dróg, osad, miast i kartę kosztów budowy. Plansza, na której toczy się rozgrywka składa się z 19 sześciokątnych pól z różnymi surowcami. Dla początkujących instrukcja sugeruje ułożenie heksów w jeden, konkretny sposób, a w miarę zdobywania doświadczenia pola można rozdysponowywać w dowolnej kolejności. Na każde z tych pól nakładane są znaczniki z literami alfabetu, które odkrywamy pokazując wartości liczbowe od 2 do 12. Celem gracza jest uzbieranie 10 punktów, gdzie wybudowanie osady jest wycenione na 1 punkt, a miasta zaś za 2 punkty.",
    photo: catan,
  },
  {
    id: 2,
    productName: "Gra o tron - gra planszowa",
    postDescription:
      "Gra o Tron – Gra Planoszowa, doczekała się drugiej edycji i to właśnie ją będę recenzować w poniższym tekście. Jest to gra strategiczna z elementami dyplomacji, intryg itp. A raczej gra dyplomatyczna z elementami strategii. Albo jedno i drugie – zależy od podejścia graczy. W naszym gronie, olbrzymia część rozgrywki dzieje się nad strołem. Sojusze są zawierane, by turę później zostały złamane jakimś wyuzdanym ciosem pod żebro. Ale o samej rozgrywce trochę później. Teraz czas na kilka suchych faktów. W grę siądziemy w ekipie od 3 do 6 graczy, jednak poniżej 5 (bez dodatku dla 4) nie ma raczej co siadać. Gra mocno traci z kilku powodów. Po pierwsze, słabo się skaluje. Po drugie, mniejsza ilość sojuszów, które można złamać (lub ich brak). Twórcą jest Christian T. Petersen, czyli gość od takich hitów jak Twilight Imperium, Star Craft, czy Star Wars: Armada. Nie powiem, podziwiam gościa. Podczas rozgrywki wcielimy się w Lordów najważniejszych rodów Westeros, czyli Lannisterów, Baratheonów, Greyjoy’ów, Starków, Tyrellów lub Martellów. Gra każdym z nich jest znacząco inna. Najważniejszą różnicą jest startowa pozycja na mapie. To ona definiuje z kim utworzymy pierwszy sojusz i z kim będziemy konkurować o zasoby, no i najważniejsze – z kim będziemy walczyć.",
    photo: got,
  },
  {
    id: 3,
    productName: "Projekt Gaja",
    postDescription:
      "Pudełko Projektu Gaja do najmniejszych nie należy. Do Gloomhaven mu daleko, ale szerokością przebija chociażby Cywilizację: Poprzez Wieki. Zdobią je grafiki, a jakże, Dennisa Lohausena, dokładnie tego samego człowieka, który odpowiadał za szatę graficzną TM. Tym razem jednak są one jakby mniej udane. Jeśli obraz pokrywający front jeszcze do mnie przemawia, jest klimatyczny, oddaje istotę Projektu jakim jest przekształcanie transplanet, tak wizerunki niektórych nacji występujących w grze, które znajdziemy na bokach, wydają się niedopracowane lub sklecone na szybko, bez pomysłu. Na szczęście wnętrze pozwala zapomnieć o wszelkich mankamentach graficznych, przynajmniej do czasu zapoznania się z planszami frakcji.  Komponenty po prostu wylewają się ze środka! Radzę dokładnie opracować system ich układania, żeby nie ryzykować wybrzuszania się wieka, a najlepiej zainwestować w insert. Ale co właściwie przyprawia o ten ból głowy? Cóż, początkowo miałem zamiar wymieniać je wszystkie, jak mam w zwyczaju, lecz uznałem, że liczba 680 lepiej zadziała na wyobraźnię. A dokładnie tyle różnego rodzaju komponentów z tektury, plastiku i papieru zostało upchanych w niecałych 7 dm³ objętości pudełka.  I w całym tym bogactwie, które cieszy oczy, tylko plansza punktowania zaburza moje zamiłowanie do figur foremnych, ale mogę już chyba ten fakt przemilczeć.Byłbym zapomniał o instrukcji, a właściwie instrukcjach. Pierwsza, główna, jest obszerna i bardzo dobrze napisana. Zawiera pięciostronicowy dodatek wyjaśniający wszyściutkie zdolności frakcji, poziomy z planszy rozwoju, pola akcji mocy i KIK-ów, żetony wzmocnienia, żetony punktowania rundy oraz pozostałe znaczki i ikonki, które mogą budzić wątpliwości. Nikt więc nie będzie mógł się zasłonić nieznajomością prawa.  Druga, skromniejsza, przybliża zasady gry z Automą. Mimo zdecydowanie mniejszych rozmiarów, może stanowić wyzwanie dla czytelnika, zwłaszcza rzadko grającego samotnie. Wystarczy jednak odrobina cierpliwości i karta pomocy by przeskoczyć ten płot. Do trybu solo powrócę jeszcze w dalszej części recenzji, a teraz bierzmy się za przygotowanie.",
    photo: gaja,
  },
  {
    id: 4,
    productName: "Terra Mystica",
    postDescription:
      "Pierwsze zetknięcie z Terra Mystica daje efekt terapii szokowej. Gra wydaje się niesamowicie złożona, oparta na wielu odmiennych mechanizmach, których ogarnięcie wydaje się wykraczać poza możliwości przeciętnego gracza, nie wspominając już o niedzielnych graczach mojego pokroju. Słyszałem o tej grze dużo dobrego, dlatego jakoś przemogłem moje rosnące przerażenie nawałą tłumaczonych zasad i zacząłem grać. Była to dobra decyzja. Tak, mechanizmy Terra Mystica są złożone. Tak, nie pomaga w tym wszystkim fakt, że każdy z graczy ma jakieś obowiązujące go zasady specjalne. Ale gdy już zaczniesz grać, błyskawicznie odkryjesz, że te wszystkie zasady są niesamowicie dobrze przemyślane i stanowią świetnie dopasowane części bardzo wydajnej i dobrze przemyślanej machiny. Wszystko tu do siebie pasuje, jedno z drugiego wynika i tworzy naprawdę ciekawy system. Terra to czystej wody gra ekonomiczna ubrana dla niepoznaki w szaty fantasy. Gra toczy się przez sześć tur, w których gracze naprzemiennie wykonują ruchy, aż do chwili gdy wszyscy spasują – zwykle dlatego, że nie stać ich już na wykonanie kolejnych. Na początku każdej tury gracze zdobywają szereg zasobów – złota, robotników, many i kapłanów – ze swoich budowli.  Następnie mogą przekształcić te zasoby na kolejne budowle, kult bogów lub rozwój cywilizacyjny (żeglugę, pozwalającą budować na bardziej odległych polach oraz przemysł umożliwiający tańszy terraforming). Wspomniany terraforming to jedyny sposób na sensowną rozbudowę – plansza złożona jest z siedmiu rodzajów pól, a każdy gracz może budować tylko na polu swojego rodzaju. Może też przekształcać rodzaj pola stosując terraforming, ale to zwykle kosztuje go robotników.",
    photo: terra,
  },
];
